# Generated by Django 5.1.7 on 2025-07-22 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/description of the verification batch', max_length=200)),
                ('email_count', models.PositiveIntegerField(default=0, help_text='Number of emails in this verification batch')),
                ('verified_emails', models.JSONField(default=dict, help_text='JSON data containing all verified email results')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='completed', max_length=20)),
                ('credits_used', models.PositiveIntegerField(default=0, help_text='Number of credits used for this verification')),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('catchall_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification History',
                'verbose_name_plural': 'Email Verification Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VerifiedEmail',
        ),
    ]
