# Generated by Django 5.1.7 on 2025-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reward_claim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
