# Generated by Django 5.1.7 on 2025-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_last_reward_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_credits',
            field=models.IntegerField(default=500),
        ),
    ]
