# Generated by Django 5.1.7 on 2025-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_claimed_free_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify_credits',
            field=models.IntegerField(default=100),
        ),
    ]
