# Generated by Django 5.1.7 on 2025-07-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_verify_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_package',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='claimed_free_verifier_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scraper_package',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verifier_package',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
