# Generated by Django 5.1.7 on 2025-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_verifier_package_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verifier_is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verifier_subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verifier_subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
