# Generated by Django 5.1.7 on 2025-04-13 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedEmailResult',
            new_name='ScrapedFromGoogle',
        ),
    ]
