# Generated by Django 5.1.7 on 2025-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_scrapedemailresult_scrapedfromgoogle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedfromgoogle',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scrapedfromgoogle',
            name='emails',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedfromgoogle',
            name='urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
